import React from 'react';

// Define the symptoms data
const symptomsData = [
  { value: 'itching', label: 'itching' },
  { value: 'skin rash', label: 'skin rash' },
  { value: 'nodal skin eruptions', label: 'nodal skin eruptions' },
  { value: 'continuous sneezing', label: 'continuous sneezing' },
  { value: 'shivering', label: 'shivering' },
  { value: 'chills', label: 'chills' },
  { value: 'joint pain', label: 'joint pain' },
  { value: 'stomach pain', label: 'stomach pain' },
  { value: 'acidity', label: 'acidity' },
  { value: 'ulcers on tongue', label: 'ulcers on tongue' },
  { value: 'muscle wasting', label: 'muscle wasting' },
  { value: 'vomiting', label: 'vomiting' },
  { value: 'burning micturition', label: 'burning micturition' },
  { value: 'spotting urination', label: 'spotting urination' },
  { value: 'fatigue', label: 'fatigue' },
  { value: 'weight gain', label: 'weight gain' },
  { value: 'anxiety', label: 'anxiety' },
  { value: 'cold hands and feets', label: 'cold hands and feets' },
  { value: 'mood swings', label: 'mood swings' },
  { value: 'weight loss', label: 'weight loss' },
  { value: 'restlessness', label: 'restlessness' },
  { value: 'lethargy', label: 'lethargy' },
  { value: 'patches in throat', label: 'patches in throat' },
  { value: 'irregular sugar level', label: 'irregular sugar level' },
  { value: 'cough', label: 'cough' },
  { value: 'high fever', label: 'high fever' },
  { value: 'sunken eyes', label: 'sunken eyes' },
  { value: 'breathlessness', label: 'breathlessness' },
  { value: 'sweating', label: 'sweating' },
  { value: 'dehydration', label: 'dehydration' },
  { value: 'indigestion', label: 'indigestion' },
  { value: 'headache', label: 'headache' },
  { value: 'yellowish skin', label: 'yellowish skin' },
  { value: 'dark urine', label: 'dark urine' },
  { value: 'nausea', label: 'nausea' },
  { value: 'loss of appetite', label: 'loss of appetite' },
  { value: 'pain behind the eyes', label: 'pain behind the eyes' },
  { value: 'back pain', label: 'back pain' },
  { value: 'constipation', label: 'constipation' },
  { value: 'abdominal pain', label: 'abdominal pain' },
  { value: 'diarrhoea', label: 'diarrhoea' },
  { value: 'mild fever', label: 'mild fever' },
  { value: 'yellow urine', label: 'yellow urine' },
  { value: 'yellowing of eyes', label: 'yellowing of eyes' },
  { value: 'acute liver failure', label: 'acute liver failure' },
  { value: 'fluid overload', label: 'fluid overload' },
  { value: 'swelling of stomach', label: 'swelling of stomach' },
  { value: 'swelled lymph nodes', label: 'swelled lymph nodes' },
  { value: 'malaise', label: 'malaise' },
  { value: 'blurred and distorted vision', label: 'blurred and distorted vision' },
  { value: 'phlegm', label: 'phlegm' },
  { value: 'throat irritation', label: 'throat irritation' },
  { value: 'redness of eyes', label: 'redness of eyes' },
  { value: 'sinus pressure', label: 'sinus pressure' },
  { value: 'runny nose', label: 'runny nose' },
  { value: 'congestion', label: 'congestion' },
  { value: 'chest pain', label: 'chest pain' },
  { value: 'weakness in limbs', label: 'weakness in limbs' },
  { value: 'fast heart rate', label: 'fast heart rate' },
  { value: 'pain during bowel movements', label: 'pain during bowel movements' },
  { value: 'pain in anal region', label: 'pain in anal region' },
  { value: 'bloody stool', label: 'bloody stool' },
  { value: 'irritation in anus', label: 'irritation in anus' },
  { value: 'neck pain', label: 'neck pain' },
  { value: 'dizziness', label: 'dizziness' },
  { value: 'cramps', label: 'cramps' },
  { value: 'bruising', label: 'bruising' },
  { value: 'obesity', label: 'obesity' },
  { value: 'swollen legs', label: 'swollen legs' },
  { value: 'swollen blood vessels', label: 'swollen blood vessels' },
  { value: 'puffy face and eyes', label: 'puffy face and eyes' },
  { value: 'enlarged thyroid', label: 'enlarged thyroid' },
  { value: 'brittle nails', label: 'brittle nails' },
  { value: 'swollen extremeties', label: 'swollen extremeties' },
  { value: 'excessive hunger', label: 'excessive hunger' },
  { value: 'extra marital contacts', label: 'extra marital contacts' },
  { value: 'drying and tingling lips', label: 'drying and tingling lips' },
  { value: 'slurred speech', label: 'slurred speech' },
  { value: 'knee pain', label: 'knee pain' },
  { value: 'hip joint pain', label: 'hip joint pain' },
  { value: 'muscle weakness', label: 'muscle weakness' },
  { value: 'stiff neck', label: 'stiff neck' },
  { value: 'swelling joints', label: 'swelling joints' },
  { value: 'movement stiffness', label: 'movement stiffness' },
  { value: 'spinning movements', label: 'spinning movements' },
  { value: 'loss of balance', label: 'loss of balance' },
  { value: 'unsteadiness', label: 'unsteadiness' },
  { value: 'weakness of one body side', label: 'weakness of one body side' },
  { value: 'loss of smell', label: 'loss of smell' },
  { value: 'bladder discomfort', label: 'bladder discomfort' },
  { value: 'foul smell of urine', label: 'foul smell of urine' },
  { value: 'continuous feel of urine', label: 'continuous feel of urine' },
  { value: 'passage of gases', label: 'passage of gases' },
  { value: 'internal itching', label: 'internal itching' },
  { value: 'toxic look (typhos)', label: 'toxic look (typhos)' },
  { value: 'depression', label: 'depression' },
  { value: 'irritability', label: 'irritability' },
  { value: 'muscle pain', label: 'muscle pain' },
  { value: 'altered sensorium', label: 'altered sensorium' },
  { value: 'red spots over body', label: 'red spots over body' },
  { value: 'belly pain', label: 'belly pain' },
  { value: 'abnormal menstruation', label: 'abnormal menstruation' },
  { value: 'dischromic patches', label: 'dischromic patches' },
  { value: 'watering from eyes', label: 'watering from eyes' },
  { value: 'increased appetite', label: 'increased appetite' },
  { value: 'polyuria', label: 'polyuria' },
  { value: 'family history', label: 'family history' },
  { value: 'mucoid sputum', label: 'mucoid sputum' },
  { value: 'rusty sputum', label: 'rusty sputum' },
  { value: 'lack of concentration', label: 'lack of concentration' },
  { value: 'visual disturbances', label: 'visual disturbances' },
  { value: 'receiving blood transfusion', label: 'receiving blood transfusion' },
  { value: 'receiving unsterile injections', label: 'receiving unsterile injections' },
  { value: 'coma', label: 'coma' },
  { value: 'stomach bleeding', label: 'stomach bleeding' },
  { value: 'distention of abdomen', label: 'distention of abdomen' },
  { value: 'history of alcohol consumption', label: 'history of alcohol consumption' },
  { value: 'fluid overload.1', label: 'fluid overload.1' },
  { value: 'blood in sputum', label: 'blood in sputum' },
  { value: 'prominent veins on calf', label: 'prominent veins on calf' },
  { value: 'palpitations', label: 'palpitations' },
  { value: 'painful walking', label: 'painful walking' },
  { value: 'pus filled pimples', label: 'pus filled pimples' },
  { value: 'blackheads', label: 'blackheads' },
  { value: 'scurring', label: 'scurring' },
  { value: 'skin peeling', label: 'skin peeling' },
  { value: 'silver like dusting', label: 'silver like dusting' },
  { value: 'small dents in nails', label: 'small dents in nails' },
  { value: 'inflammatory nails', label: 'inflammatory nails' },
  { value: 'blister', label: 'blister' },
  { value: 'red sore around nose', label: 'red sore around nose' },
  { value: 'yellow crust ooze', label: 'yellow crust ooze' }
];

export default symptomsData;
