# Generated by Django 5.0.1 on 2024-03-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profile_height_profile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
